# Security Scan

trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOTNET_VERSION: '8.x'

stages:
- stage: SecurityScans
  displayName: Security Scans
  jobs:
  - job: RunScans
    displayName: Run Semgrep, Gitleaks, Dependency-Check
    steps:

    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: sdk
        version: $(DOTNET_VERSION)

    - checkout: self

    - script: |
        dotnet restore
      displayName: 'Restore NuGet Packages'

    # Semgrep
    - script: |
        pip install semgrep
      displayName: 'Install Semgrep'

    - script: |
        semgrep scan --config auto --error
      displayName: 'Run Semgrep Scan'

    # OWASP dependency scan via Docker
    - script: |
        docker run --rm \
          --env NVD_API_KEY=$(NVD_API_KEY) \
          alpine sh -c 'echo "NVD_API_KEY inside container is: ${NVD_API_KEY:+set}"'
      displayName: 'Verify NVD_API_KEY accessible in docker'

    - script: |
        export NVD_API_KEY=$(NVD_API_KEY)
        docker run --rm \
          -e NVD_API_KEY=$NVD_API_KEY \
          -v $(Build.SourcesDirectory):/src \
          -v $(Build.ArtifactStagingDirectory):/report \
          owasp/dependency-check:latest \
          --project "AzureFunctionApp" \
          --scan /src \
          --format HTML \
          --enableRetired \
          --failOnCVSS 11 \
          --failOnNone \
          --out /report \
          --log /report/debug.log
      displayName: 'Run OWASP Dependency-Check with explicitly passed API key'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Dependency-Check Report'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'DependencyReport'

    # Gitleaks
    - script: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin
      displayName: 'Install Gitleaks'

    - script: |
        gitleaks detect --source $(Build.SourcesDirectory) --report-path $(Build.ArtifactStagingDirectory)/gitleaks-report.json --no-banner
      displayName: 'Run Gitleaks'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Gitleaks Report'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/gitleaks-report.json'
        ArtifactName: 'GitleaksReport'

    # OWASP ZAP (optional, requires accessible endpoint)
    - script: |
        docker run -v $(Build.SourcesDirectory):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
          -t https://your-function-url.azurewebsites.net \
          -r zap-report.html
      displayName: 'Run ZAP Baseline Scan'
      condition: false  # Change to 'true' or remove this line to enable

    - task: PublishBuildArtifacts@1
      displayName: 'Publish ZAP Report'
      condition: false
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/zap-report.html'
        ArtifactName: 'ZAPReport'
